### ISSUE TITLE
Exclude regions from diff

### ISSUE THREAD

**Issue by maiers** [moshensky/pdf-visual-diff#15]
It would be interesting to be able to exclude specific regions (containing for example the print date) from the diff. Would this be possible any way?

(Anyway it's a nice tool)

**Comment by moshensky** [comment]
Hi @maiers, one of the simplest solutions that I can see is to provide an option to define a rectangle that will always be of some solid color, but is it really needed? I initially created this lib to be able to test that some generated documents from templates don't get accidentally changed. For that reason I am able for my own use cases to use data that is not changing. What is your particular use case?

**Comment by maiers** [comment]
We generate a pdf report with the current date in the footer. While we could potentially fix the date for the tests, it would be nice to minimize interfering with the system under test.

**Comment by moshensky** [comment]
So would a solid rectangle defined by `x0, y0, x1, y1` coordinates would be of any use to you?
Something like
```
comparePdfToSnapshot(pathToPdf, __dirname, 'my-awesome-report', {
  maskRegions: [{
    type: 'rectangle',
    x0: 300,
    y0: 200,
    x1: 330,
    y1: 210,
    color: 'black'
  }]
})
```

Where coordinates will depend on the pdf at hand. Pdfs are converted to images using 300dpi. Some trial and errors might be needed to pinpoint the date.

**Comment by maiers** [comment]
I believe this would be a sufficiently flexible solution.

**Comment by moshensky** [comment]
Good. I will add it over the weekend.

**Comment by moshensky** [comment]
@maiers, I have released new version with possibility to mask regions. Please check it out.

Options changed a bit to:

```
export type RectangleMask = Readonly<{
  type: 'rectangle-mask'
  x: number
  y: number
  width: number
  height: number
  color: HighlightColor
}>
```

example: 
```
    comparePdfToSnapshot(singlePagePdfPath, __dirname, 'rectangle-masks', {
      maskRegions: [
        {
          type: 'rectangle-mask',
          x: 120,
          y: 150,
          width: 280,
          height: 200,
          color: 'Blue',
        },
      ],
    })
```

Many rectangle regions could be passed in.

**Comment by moshensky** [comment]
Closing. Feel free to reopen.
