### ISSUE TITLE
Fails to generate an initial snapshot with jest

### ISSUE THREAD

**Issue by badigina-merck** [moshensky/pdf-visual-diff#26]
When using with jest, test fails to generate an initial snapshot.

The error:

> Error: Command failed: execvp failed, errno = 2 (No such file or directory)
> gm convert: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r300x300" "-sOutputFile=/var/folders/sp/gcjtmys9119gmypdthgqlnf56sxk7_/T/gm8P4mXA" "--" "/var/folders/sp/gcjtmys9119gmypdthgqlnf56sxk7_/T/gmSIOddt" "-c" "quit".
> gm convert: Postscript delegate failed (/var/folders/sp/gcjtmys9119gmypdthgqlnf56sxk7_/T/gm3uZQeX).
> 
> 
>     at ChildProcess.onExit (/<...>/node_modules/gm/lib/command.js:301:17)
>     at ChildProcess.emit (events.js:315:20)
>     at ChildProcess.EventEmitter.emit (domain.js:467:12)
>     at maybeClose (internal/child_process.js:1048:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

Test suit:

```
describe("X report", () => {
  /* PDF generator setup and teardown */

  it("should be generated correctly", async () => {
    const reportBuffer = await generatePdfToBuffer()
    await expect(reportBuffer).toMatchPdfSnapshot()
  })
})
```

My package.json

```
{
  "engines": {
    "node": ">= 14.15.4"
  },
  "dependencies": {
    <...>
    "puppeteer": "^10.1.0",
  },
  "devDependencies": {
     <...>
    "jest": "^26.6.3",
    "jest-circus": "^26.6.3",
    "jest-image-snapshot": "^4.5.0",
    "pdf-visual-diff": "^0.5.0"
  }
}
```

**Comment by moshensky** [comment]
Hi, I will have a look later today.

**Comment by jonyw4** [comment]
To work in mac I need it run `brew install graphicsmagick ghostscript`

**Comment by badigina-merck** [comment]
> To work in mac I need it run `brew install graphicsmagick ghostscript`

That fix the issue for me, thank you!

**Comment by badigina-merck** [comment]
Would be nice to update readme with this info :)

**Comment by moshensky** [comment]
Hi,

sorry for not being able to provide any help. I am on a vacation till end
of August. I hope to be more helpful when I'm back.
