### ISSUE TITLE
Diff in different OS

### ISSUE THREAD

**Issue by jonyw4** [moshensky/pdf-visual-diff#27]
Hi guys, amazing project!

I generate some images using macOS 11.5.2 with `graphicsmagick ghostscript` in Rosetta, and then, when I run in Ubuntu 20 (Github action default ubuntu) I have a slight change in some pixel and that fail the test. I could increase the tolerance, but I want to have a pixel-perfect comparison. Do you know if `graphicsmagick` has something to do with this? Do you know what I could do to not achieve this problem?

**Comment by jonyw4** [comment]
I saw this article maybe is related to that
http://jeromebelleman.gitlab.io/posts/graphics/gmpdf/

**Comment by badigina-merck** [comment]
Same for me when running tests in CI (jenkins + docker) VS snapshot created locally on Mac

**Comment by Its-Alex** [comment]
@moshensky Up?

**Comment by moshensky** [comment]
I will look into it and write back in a few days.

**Comment by moshensky** [comment]
This has to do something with the conversion of pdfs to images, where it seems some colors could differ a tiny bit. In my tests setting `tolerance: 0.0000001` solves it. 
I'm curious to look at your pdfs and relevant expected images that fail, if you could share them.
For the time being I'm thinking whether to change default tolerance to the above number.

**Comment by moshensky** [comment]
So far for pixel perfect comparison same versions of graphicsmagick (maybe gs as well) need to be used everywhere. I was not able to find any reliable options for convert that would work between versions 1.3.35 and 1.3.38.

**Comment by moshensky** [comment]
I have updated how images are generated. My initial tests are successful. Most probably tomorrow I will release new version. Unfortunately all snapshots will have to be regenerated.

**Comment by moshensky** [comment]
Should be solved by latest two versions.
