### ISSUE TITLE
Snapshot images generated by latest version (0.6.0) are missing text

### ISSUE THREAD

**Issue by arsalansufi** [moshensky/pdf-visual-diff#46]
Hello! I recently upgraded to the latest version of pdf-visual-diff (from 0.5.0 to 0.6.0) with the hopes of addressing https://github.com/moshensky/pdf-visual-diff/issues/27. Unfortunately, my new snapshot images are missing text. Below are some sample images (left is before, right is after):

<img src='https://user-images.githubusercontent.com/12616928/171953336-7239e4f9-0a8d-4153-a3e1-60c420fde881.png' alt='before' width=300 /> <img src='https://user-images.githubusercontent.com/12616928/171953338-ce4aa04e-d2dc-42ad-95b2-1b40f8ead43a.png' alt='after' width=300 />

I haven't changed how I'm rendering the snapshot images:

```ts
import jsPDF from 'jspdf'

const generatePDF = async () => {
  const doc = new jsPDF({ format: 'letter', unit: 'pt' });

  // Draw PDF contents...

  await doc.save(fileName, { returnPromise: true });
  return doc.output();
};

test('Generating PDF', async () => {
  const pdf = await generatePDF();
  await expect(Buffer.from(pdf)).toMatchPdfSnapshot();
});
```

This could potentially be related to https://github.com/mozilla/pdf.js/issues/14982? Appreciate any insights and am happy to provide additional details as needed!

**Comment by moshensky** [comment]
Hello @arsalansufi,

may I ask for the pdf file?

**Comment by no-man-is-an-island** [comment]
Hitting the same issue, only on the latest version! Any update on this one?

**Comment by moshensky** [comment]
@no-man-is-an-island can you attach a sample pdf with the problem please?

**Comment by moshensky** [comment]
Closing due to lack of reference files to use for testing and fixing.
Please feel free to reopen.
