### ISSUE TITLE
Crash on Nodejs18

### ISSUE THREAD

**Issue by xahhy** [moshensky/pdf-visual-diff#48]
We met the exact same issue as follows

https://github.com/Automattic/node-canvas/issues/2069#issuecomment-1296096477

And it requires to upgrade the canvas version to fix it

**Comment by moshensky** [comment]
@xahhy thanks for reporting it. I will have a look later today.

**Comment by moshensky** [comment]
@xahhy I have published new version with updated dependencies. Please check if it will work for you.
