### ISSUE TITLE
maskRegions not supported for multi-page pdf

### ISSUE THREAD

**Issue by moreginger** [moshensky/pdf-visual-diff#51]
Firstly, thanks so much for doing this, it's so close to solving my problem!

The remaining issue is that I need to mask a region containing the time the pdf was generated. However, `maskRegions` is not applied when there are multiple pages in the pdf (it would be good to at least document this).

It would be amazing to have some way to use `maskRegions`... either page at a time diff as per #1, or different masks per page, or a way to force the same mask on every page.

Meanwhile I'll try to tune the tolerance for now.

**Comment by moshensky** [comment]
Thanks for reporting it. I will have a look into it. At the very least will make sure to update the docs, but will try to make it work first.

**Comment by moshensky** [comment]
@moreginger unfortunately it is not possible to define mask per page. Right now multi page pdf is being converted to a single image containing all the pages one after another. Without implementing issue that you have mentioned, your only option is to add an array with masks with coordinates for each specific page. If your pages are same height and you want to mask same region everywhere, then you could simply generate that array by updating the `y` coordinate with a constant.

**Comment by moreginger** [comment]
@moshensky - passing a mask per page sounds fine to me. It looks like the masks are applied before the images are concatenated, so I don't think you'd need to offset each page? Currently, if there is more than one image (page) then it doesn't apply the mask at all: https://github.com/moshensky/pdf-visual-diff/blob/master/src/compare-pdf-to-snapshot.ts#L34

I can try to propose a PR if you'd like. The tricky bit is deciding the API for `maskRegions`. Should it require an `MaskRegions` per page, or should `RectangleMask` have an optional page property (otherwise applying it to every page), or something else? Changing `RectangleMask` to have an optional page property might be a good way to avoid breaking your current API.

**Comment by moshensky** [comment]
@moreginger thank you for pointing me to the root cause. I took the liberty to break the interface and update the code right away.

I have released a new version `0.8.0` please have a look and see whether it will work for you.  You can see in the tests a [sample usage](https://github.com/moshensky/pdf-visual-diff/blob/master/src/compare-pdf-to-snapshot.spec.ts#L105). 

Don't take my change as an unwillingness to have more contributors to the code base and feel welcomed to contribute to the project!

**Comment by moshensky** [comment]
Unless it becomes a big pain point for someone I don't consider doing any changes right now due to some other priorities.
